# This is the full list of 64 options items currently used in the spending categories column of the research object.
RESEARCH_OBC_VALUES = [
    "Abortion",
    "Agriculture (seeds, fertilizers)",
    "Alcohol or drugs",
    "Benefitting the girl child",
    "Building a house",
    "Buying/renting land",
    "Buying clothes/furniture for your house",
    "Buying more things for an existing business",
    "Church tithes/religious donations",
    "Commercial sex",
    "Don't know, no response",
    "Education for others (e.g. your children)",
    "Education for yourself",
    "Energy",
    "Equipment/services to support armed groups",
    "Farming produce (e.g. plants, grains)",
    "Food",
    "Gambling",
    "Gifts",
    "Health/medical expenses",
    "Hiring",
    "I don't know",
    "Improving your house (e.g. new roof)",
    "Improving your house (e.g. new roof), including repairs",
    "I saved some of my money",
    "Leisure",
    "Livestock (goats, sheep, cows, chickens)",
    "Livestock (goats, sheep, cows, chickens), including veterinary treatment",
    "Machinery and equipment",
    "Marketing and branding",
    "Moving",
    "Other",
    "Paying back loans or debts",
    "Product certificates (e.g. ONSSA)",
    "Products distribution",
    "Qat",
    "Rehabilitation of fields/property",
    "Renting a house/apartment",
    "Repair of assets (boats or other equipment)",
    "Sanitation",
    "Social event / wedding",
    "Staff skills training",
    "Starting a new business",
    "Support of terrorism",
    "Tools and equipment",
    "Transportation to school",
    "We haven't spent the money yet",
    "Relocate permanently (>1 month)",
    "Till the land",
    "Drain water from fields",
    "Temporarily leaving the area (<1 month)",
    "Preparing for floods",
    "Lending money to others",
    "Giving money to others / charity",
    "Household goods",
    "Business - Employee salaries",
    "Business - Repairing shop, office or place of work",
    "Business - Repairing business warehouse",
    "Business - Buying or repairing working tools / machines",
    "Business - Buying new inventory",
    "Business - Buying new raw materials",
    "Business - Payment of business rent/facilities",
    "Business - Other operational / business expenses",
    "Food Health/medical expenses",
]
FU_OBJ_VALUES = [
    "Livestock (goats, sheep, cows, chickens)",
    "Agriculture (seeds, fertilizers)",
    "Starting a new business",
    "Buying more things for an existing business",
    "Education for yourself",
    "Education for others (e.g. your children)",
    "Building a house",
    "Buying/renting land",
    "Improving your house (e.g. new roof)",
    "Paying back loans or debts",
    "Buying clothes/furniture for your house",
    "Church tithes/religious donations",
    "Health/medical expenses",
    "Food",
    "I saved some of my money",
    "Alcohol or drugs",
    "Gambling",
    "Commercial sex",
    "Abortion",
    "Benefitting the girl child",
    "Other",
    "Renting a house/apartment",
    "Transportation to school",
    "Machinery and equipment",
    "Farming produce (e.g. plants, grains)",
    "Staff skills training",
    "Product certificates (e.g. ONSSA)",
    "Marketing and branding",
    "Products distribution",
    "I don't know",
    "We haven't spent the money yet",
    "Social event / wedding",
    "Qat",
    "Tools and equipment",
    "Moving",
    "Equipment/services to support armed groups",
    "Support of terrorism",
    "Improving your house (e.g. new roof), including repairs",
    "Livestock (goats, sheep, cows, chickens), including veterinary treatment",
    "Rehabilitation of fields/property",
    "Repair of assets (boats or other equipment)",
    "Don't know, no response",
    "Energy",
    "Gifts",
    "Leisure",
    "Sanitation",
    "Hiring",
]


HOW_MUCH_COLS = [
    "How_Much_Spent_on_USAID_Banned_Items__c",
    "How_Much_Spent_on_Livestock__c",
    "How_Much_Spent_on__c",
    "How_Much_Spent_on_Agriculture__c",
    "How_Much_Spent_on_Existing_Business__c",
    "How_Much_Spent_on_New_Business__c",
    "How_Much_Spent_on_Self_Education__c",
    "How_Much_Spent_on_Other_Education__c",
    "How_Much_Spent_on_Building_Home__c",
    "How_Much_Spent_on_Sanitation__c",
    "How_Much_Spent_on_Loans_Debts__c",
    "How_Much_Spent_on_Savings__c",
    "How_Much_Spent_on_Rent__c",
    "How_Much_Spent_on_Energy__c",
    "How_Much_Spent_on_Food__c",
    "How_Much_Spent_on_Health__c",
    "How_Much_Spent_on_Household_Goods__c",
    "How_Much_Spent_on_Church__c",
    "How_Much_Spent_on_Events__c",
    "How_Much_Spent_on_Leisure__c",
    "How_Much_Spent_on_Gifts__c",
    "How_Much_Spent_on_Other_Items__c",
    "How_much_spent_on_land__c",
    "How_much_spent_on_improving_home__c",
    "How_much_spent_on_clothes_or_furniture__c",
    "How_much_spent_on_drugs__c",
    "How_much_spend_on_gambling__c",
    "How_much_spent_on_sex__c",
    "How_much_spent_on_abortion__c",
    "How_Much_Spent_on_Tools_Equipment__c",
    "How_Much_Unspent__c",
    "How_Much_Was_Stolen__c",
    "How_Much_Was_Bribed__c",
    "How_Much_Money_Withdrawn__c",
    "How_Much_Money_Received__c",
]
RESEARCH_SPENDING_COLS = [
    "Spending_Drugs__c",
    "Spending_Abortion__c",
    "Spending_Energy__c",
    "Spending_Events__c",
    "Spending_Existing_Business__c",
    "Spending_Food__c",
    "Spending_Gifts__c",
    "Spending_Health__c",
    "Spending_Hiring__c",
    "Spending_Household_Goods__c",
    "Spending_Improving_Home__c",
    "Spending_Land__c",
    "Spending_Loans_Debts__c",
    "Spending_New_Business__c",
    "Spending_Other_Education__c",
    "Spending_Other_Items__c",
    "Spending_Rent__c",
    "Spending_Sanitation__c",
    "Spending_Savings__c",
    "Spending_Gambling__c",
    "Spending_Agriculture__c",
    "Spending_Building_Home__c",
    "Spending_Self_Education__c",
    "Spending_Sex__c",
    "Spending_Unspent__c",
    "Spending_Total__c",
    "Spending_Leisure__c",
    "Spending_Church__c",
    "Spending_Livestock__c",
    "Spending_Clothes_Furniture__c",
    "Spending_Categories_Business_c__c",
    "Spending_Categories_Business_Other_c__c",
    "Spending_Categories_Business_Active_c__c",
    "Spending_Motorcycle_Bicycle__c",
    "Spending_Product_Distribution__c",
    "Spending_Benefit_Girl_Child__c",
    "Spending_Repair_Assets__c",
    "Spending_Terrorism__c",
    "Spending_Improving_Home_Including_Repa__c",
    "Spending_Rehabilitation_Fields_Propert__c",
    "Spending_Moving__c",
    "Spending_Categories__c",
    "Spending_Machinery_Equipment__c",
    "Spending_Marketing_Branding__c",
    "Spending_Farm_Produce__c",
    "Spending_Tools_Equipment__c",
    "Spending_Product_Certificates__c",
    "Spending_School_Transportation__c",
    "Spending_Staff_Training__c",
    "Spending_USAID_Banned_Items__c",
    "Spending_Armed_Groups__c",
    "Spending_Qat__c",
    "Spending_Categories_Other__c",
    "Spending_Livestock_Including_Vet__c",
    "Spending_Items_Regular_Agriculture__c",
]


TRANSFER_COLS = [
    "transfer_id",
    "recipient_id",
    "country",
    "continent",
    "record_type_name",
    "project_name",
    "transfer_created_date",
    "original_scheduled_date",
    "most_recent_attempt_date",
    "completed_date",
    "transfer_status",
    "discarded_duplicate",
    "recipient_inactive_stage",
    "transfer_inactive",
    "transfer_completed",
    # "transfer_amount_total_full_local_estimate",
    # "transfer_amount_total_eligible_local",
    # "transfer_amount_total_discarded_local_estimate",
    # "transfer_amount_total_full_usd_estimate",
    # "transfer_amount_total_eligible_usd",
    # "transfer_amount_total_discarded_usd_estimate",
    # "transfer_amount_total_eligible_usd_current_value",
    # "transfer_amount_total_complete_local",
    # "transfer_amount_total_outstanding_local",
    # "transfer_amount_total_complete_usd",
    # "transfer_amount_total_outstanding_usd",
    # "transfer_amount_commitment_full_local_estimate",
    # "transfer_amount_commitment_eligible_local",
    # "transfer_amount_commitment_discarded_local_estimate",
    # "transfer_amount_commitment_full_usd_estimate",
    # "transfer_amount_commitment_eligible_usd",
    # "transfer_amount_commitment_discarded_usd_estimate",
    # "transfer_amount_commitment_eligible_usd_current_value",
    # "transfer_amount_commitment_complete_local",
    # "transfer_amount_commitment_outstanding_local",
    "transfer_amount_commitment_complete_usd",
    "transfer_amount_commitment_outstanding_usd",
    "index_one_on_time",
    "index_later_delay_flup",
    "recipient_age_at_contact",
    "recipient_gender",
]

FU_ONLY = [
    "How_Much_Was_Stolen__c",
    "How_Much_Spent_on__c",
    "How_Much_Was_Bribed__c",
    "How_Much_Money_Received__c",
    "How_Much_Money_Withdrawn__c",
    "Date_of_Follow_up__c",
    "Follow_up_Type__c",
]

RES_ONLY = [
    "Spending_Armed_Groups__c",
    "Spending_Benefit_Girl_Child__c",
    "Spending_Categories_Business_Active_c__c",
    "Spending_Categories_Business_Other_c__c",
    "Spending_Categories_Business_c__c",
    "Spending_Categories_Other__c",
    "Spending_Farm_Produce__c",
    "Spending_Hiring__c",
    "Spending_Improving_Home_Including_Repa__c",
    "Spending_Items_Regular_Agriculture__c",
    "Spending_Livestock_Including_Vet__c",
    "Spending_Machinery_Equipment__c",
    "Spending_Marketing_Branding__c",
    "Spending_Motorcycle_Bicycle__c",
    "Spending_Moving__c",
    "Spending_Product_Certificates__c",
    "Spending_Product_Distribution__c",
    "Spending_Qat__c",
    "Spending_Rehabilitation_Fields_Propert__c",
    "Spending_Repair_Assets__c",
    "Spending_School_Transportation__c",
    "Spending_Staff_Training__c",
    "Spending_Terrorism__c",
    "Spending_Total__c",
]
FLUP_TO_RES = {
    "What_Did_The_Recipient_Spend_On__c": "Spending_Categories__c",
    "How_Much_Spent_on_USAID_Banned_Items__c": "Spending_USAID_Banned_Items__c",
    "How_Much_Spent_on_Livestock__c": "Spending_Livestock__c",
    "How_Much_Spent_on_Agriculture__c": "Spending_Agriculture__c",
    "How_Much_Spent_on_Existing_Business__c": "Spending_Existing_Business__c",
    "How_Much_Spent_on_New_Business__c": "Spending_New_Business__c",
    "How_Much_Spent_on_Self_Education__c": "Spending_Self_Education__c",
    "How_Much_Spent_on_Other_Education__c": "Spending_Other_Education__c",
    "How_Much_Spent_on_Building_Home__c": "Spending_Building_Home__c",
    "How_Much_Spent_on_Sanitation__c": "Spending_Sanitation__c",
    "How_Much_Spent_on_Loans_Debts__c": "Spending_Loans_Debts__c",
    "How_Much_Spent_on_Savings__c": "Spending_Savings__c",
    "How_Much_Spent_on_Rent__c": "Spending_Rent__c",
    "How_Much_Spent_on_Energy__c": "Spending_Energy__c",
    "How_Much_Spent_on_Food__c": "Spending_Food__c",
    "How_Much_Spent_on_Health__c": "Spending_Health__c",
    "How_Much_Spent_on_Household_Goods__c": "Spending_Household_Goods__c",
    "How_Much_Spent_on_Church__c": "Spending_Church__c",
    "How_Much_Spent_on_Events__c": "Spending_Events__c",
    "How_Much_Spent_on_Leisure__c": "Spending_Leisure__c",
    "How_Much_Spent_on_Gifts__c": "Spending_Gifts__c",
    "How_Much_Spent_on_Other_Items__c": "Spending_Other_Items__c",
    "How_much_spent_on_land__c": "Spending_Land__c",
    "How_much_spent_on_improving_home__c": "Spending_Improving_Home__c",
    "How_much_spent_on_clothes_or_furniture__c": "Spending_Clothes_Furniture__c",
    "How_much_spent_on_drugs__c": "Spending_Drugs__c",
    "How_much_spend_on_gambling__c": "Spending_Gambling__c",
    "How_much_spent_on_sex__c": "Spending_Sex__c",
    "How_much_spent_on_abortion__c": "Spending_Abortion__c",
    "How_Much_Spent_on_Tools_Equipment__c": "Spending_Tools_Equipment__c",
    "How_Much_Unspent__c": "Spending_Unspent__c",
}


PICK_LST_TO_QUANTS_COLS = {
    "Agriculture (seeds, fertilizers)": "spending_agriculture",
    "Rehabilitation of fields/property": "spending_rehabilitation_fields_propert",
    "Farming produce (e.g. plants, grains)": "spending_farm_produce",
    "Drain water from fields": "spending_agriculture",
    "Preparing for floods": "spending_agriculture",
    "Till the land": "spending_agriculture",
    "Starting a new business": "spending_new_business",
    "Buying more things for an existing business": "spending_existing_business",
    "Marketing and branding": "spending_marketing_branding",
    "Products distribution": "spending_product_distribution",
    "Product certificates (e.g. ONSSA)": "spending_product_certificates",
    "Staff skills training": "spending_staff_training",
    "Tools and equipment": "spending_tools_equipment",
    "Business - Buying new inventory": "spending_categories_business",
    "Business - Buying new raw materials": "spending_categories_business_active",
    "Business - Buying or repairing working tools / machines": "spending_categories_business_active",
    "Business - Employee salaries": "spending_categories_business_active",
    "Business - Other operational / business expenses": "spending_categories_business_active",
    "Business - Payment of business rent/facilities": "spending_categories_business_active",
    "Business - Repairing business warehouse": "spending_categories_business_active",
    "Business - Repairing shop, office or place of work": "spending_categories_business",
    "Paying back loans or debts": "spending_loans_debts",
    "Donations": "spending_church",
    "Gifts": "spending_gifts",
    "Church tithes/religious donations": "spending_church",
    "Giving money to others / charity": "spending_church",
    "Education for others (e.g. your children)": "spending_other_education",
    "Education for yourself": "spending_self_education",
    "Books/other educational materials": "spending_self_education",
    "Transportation to school": "spending_school_transportation",
    "Food": "spending_food",
    "Health/medical expenses": "spending_health",
    "Abortion": "spending_abortion",
    "Food Health/medical expenses": "spending_health",
    "Buying clothes/furniture for your house": "spending_clothes_furniture",
    "Household goods": "spending_household_goods",
    "Building a house": "spending_building_home",
    "Improving your house (e.g. new roof)": "spending_improving_home",
    "Improving your house (e.g. new roof), including repairs": "spending_improving_home_including_repa",
    "Renting a house/apartment": "spending_rent",
    "Buying/renting land": "spending_land",
    "Livestock (goats, sheep, cows, chickens)": "spending_livestock",
    "Livestock (goats, sheep, cows, chickens), including veterinary treatment": "spending_livestock_including_vet",
    "None": "spending_unspent",
    "Don't know, no response": "spending_unspent",
    "We haven't spent the money yet": "spending_unspent",
    "I don't know": "spending_unspent",
    "Other": "spending_other_items",
    "Qat": "spending_qat",
    "Hiring": "spending_hiring",
    "Employment": "spending_hiring",
    "Sanitation": "spending_sanitation",
    "Alcohol or drugs": "spending_drugs",
    "Substance Abuse": "spending_drugs",
    "Energy": "spending_energy",
    "Gifts": "spending_gifts",
    "Lending money to others": "spending_other_items",
    "Leisure": "spending_leisure",
    "Gambling": "spending_gambling",
    "Entertainment": "spending_leisure",
    "Social event / wedding": "spending_events",
    "Repair of assets (boats or other equipment)": "spending_repair_assets",
    "Machinery and equipment": "spending_machinery_equipment",
    "Benefitting the girl child": "spending_benefit_girl_child",
    "Equipment/services to support armed groups": "spending_armed_groups",
    "Commercial sex": "spending_sex",
    "Support of terrorism": "spending_terrorism",
    "Moving": "spending_moving",
    "Relocate permanently (>1 month)": "spending_moving",
    "Temporarily leaving the area (<1 month)": "spending_moving",
    "Social Cause": "spending_other_items",
    "I saved some of my money": "spending_savings",
}


CATEGORY_AGGREGATIONS = {
    "Agriculture": [
        "Agriculture (seeds, fertilizers)",
        "Rehabilitation of fields/property",
        "Farming produce (e.g. plants, grains)",
        "Drain water from fields",
        "Preparing for floods",
        "Till the land",
    ],
    "Sanitation": ["Sanitation"],
    "Entrepreneurship": [
        "Starting a new business",
        "Buying more things for an existing business",
        "Marketing and branding",
        "Products distribution",
        "Product certificates (e.g. ONSSA)",
        "Staff skills training",
        "Tools and equipment",
        "Business - Buying new inventory",
        "Business - Buying new raw materials",
        "Business - Buying or repairing working tools / machines",
        "Business - Employee salaries",
        "Business - Other operational / business expenses",
        "Business - Payment of business rent/facilities",
        "Business - Repairing business warehouse",
        "Business - Repairing shop, office or place of work",
    ],
    "Debt": ["Paying back loans or debts"],
    "Donations": [
        "Donations",
        "Church tithes/religious donations",
        "Giving money to others / charity",
    ],
    "Education": [
        "Education for others (e.g. your children)",
        "Education for yourself",
        "Transportation to school",
        "Books/other educational materials",
    ],
    "Employment": ["Hiring", "Employment"],
    "Entertainment": ["Leisure", "Gambling", "Entertainment", "Social event / wedding"],
    "Food": ["Food"],
    "Gifts": [
        "Gifts",
        "Lending money to others",
    ],
    "Healthcare": [
        "Health/medical expenses",
        "Abortion",
        "Food Health/medical expenses",
    ],
    "Household": [
        "Buying clothes/furniture for your house",
        "Household goods",
    ],
    "Housing": [
        "Building a house",
        "Improving your house (e.g. new roof)",
        "Improving your house (e.g. new roof), including repairs",
        "Renting a house/apartment",
        "Buying/renting land",
    ],
    "Illegal Activities": [
        "Commercial sex",
        "Equipment/services to support armed groups",
        "Support of terrorism",
    ],
    "Livestock": [
        "Livestock (goats, sheep, cows, chickens)",
        "Livestock (goats, sheep, cows, chickens), including veterinary treatment",
    ],
    "Repair Assets": [
        "Repair of assets (boats or other equipment)",
        "Machinery and equipment",
    ],
    "None": [
        "None",
        "Don't know, no response",
        "We haven't spent the money yet",
        "I don't know",
    ],
    "Other": ["Other", "Qat"],
    "Moving": [
        "Moving",
        "Relocate permanently (>1 month)",
        "Temporarily leaving the area (<1 month)",
    ],
    "Savings": ["I saved some of my money"],
    "Social Cause": ["Social Cause", "Benefitting the girl child"],
    "Substance Abuse": ["Alcohol or drugs", "Substance Abuse"],
    "Energy": ["Energy"],
}

# For now, grouping a bunch of cats under other
ALL_OTHER = [
    "Employment",
    "Sanitation",
    "Substance Abuse",
    "Energy",
    "Gifts",
    "Entertainment",
    "Repair Assets",
    "Social Cause",
    "Moving",
    "Illegal Activities",
    "Donations",
    "None"
]


ABBREVIATIONS = {
    "Obs.": "N",
    "Agriculture": "Agri",
    "Debt": "Dbt",
    "Education": "Edu",
    "Entrepreneurship": "Ent",
    "Food": "Fd",
    "Healthcare": "HC",
    "Household": "HH",
    "Housing": "Hou",
    "Livestock": "Lstk",
    "Other": "Oth",
    "Savings": "Sav",
}
